Formatting
Covid19-Resource-Matching/web pull request #6
Opened 2020-04-13 06:52 UTC by y3l2n

ran black on all files to clean things up

2020-04-13 06:53 UTC, y3l2n commented
added poetry & formatted files

2020-04-13 23:08 UTC, Lucretiel requested changes
Recommend reverting the changes in /covid/migrations, since those files are auto-generated. In the PR that adds black we should configure it to ignore that directory permanently.

2020-04-13 23:08 UTC, Lucretiel commented on backend/pyproject.toml
> +[tool.poetry.dev-dependencies]
This would be the place to add `black`

2020-04-22 05:04 UTC, y3l2n commented on backend/pyproject.toml
> +[tool.poetry.dev-dependencies]
done.

2020-04-22 05:05 UTC, y3l2n commented
also reverted migrations formatting.

2020-05-12 05:39 UTC, y3l2n commented
@Lucretiel ping on review?

2020-05-14 04:02 UTC, Lucretiel approved these changes

2020-05-15 03:15 UTC, merged